disabled_rules:
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  
opt_in_rules:
  - empty_count
  - missing_docs

excluded:
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift


force_cast: warning
force_try:
  severity: warning

line_length: 200

type_body_length:
  - 300
  - 400

file_length:
  warning: 500
  error: 700

type_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
variable_name:
  min_length:
    error: 2
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
