# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'

target 'Kiwee' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kiwee
  pod 'Kingfisher', '~> 7.6.0'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftLint'

end
