# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

target 'Kiwee' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for STYLiSH
  pod 'Kingfisher', '~> 7.6.0'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftLint'
  
end

